const socket = io.connect('http://192.168.2.207:3000')
box = document.getElementById('box')

const clientGreeting = 'connected to client...'

// The socket.on('connect') is an event which is fired upon a successful connection from the web browser
// We then have a function callback that will send to the server the hello world message.
socket.on('connect', function () {
  socket.emit('join', clientGreeting)
})

socket.on('broad', function (data) {
  const p = document.createElement('p')
  p.textContent = data
  box.appendChild(p)
  box.scrollTop = box.scrollHeight
})

socket.on('clearBox', function () {
  box.innerHTML = ''
})

// receive any keypress event from client and send to server
// the goal of this function is to simulate a raspberry pi sensor digital output,
// in this case the signal is generated by client
function simulateSensorSignal () {
  socket.emit('signal', new Date())
}
